# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cac7b569ef0753abcebb25657c0a89250e820a5420a86064f6d39bf4f5f87c7f7dbf5efae3e97d256eb1b0e273f26f4bea8ed36e7abe23cd090027a6f2960c9c

test:
  secret_key_base: 7f8dec3d5f41055a5794551ea44701d55d92aefcb1dd6a080de8ddb8e24c4a6ec139de320ea7cd38442f4d06c3e6f909419785b838b71465673fdbb85dc026f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
